/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registrationclassadvice;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


/**
 *
 * @author Daniel Nguyen
 */
public class List extends javax.swing.JFrame {

    /**
     * Creates new form List
     */
    public List() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(153, 255, 153));
        setIconImages(null);

        jButton1.setLabel("Reply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("List Posts for Advice");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setText("View Replies");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(97, 97, 97))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss");
Calendar cal = Calendar.getInstance();
 ArrayList list = new ArrayList();
       
 ArrayList dateList = new ArrayList();
 String dateTime[] ;


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        int position;
//        String[] dateRegister;
//       
//       
//        if( jCheckBox1.isSelected())
//        {
//           
//            list.add("SE 46A");
//            String date = dateFormat.format(cal.getTime());
//            dateList.add(date);
//            
//        }
//        if( jCheckBox2.isSelected())
//        {
//            list.add("SE 46B");
//            String date = dateFormat.format(cal.getTime());
//            dateList.add(date);
//            
//        }
//        if( jCheckBox3.isSelected())
//        {
//            list.add("SE 131");
//            String date = dateFormat.format(cal.getTime());
//            dateList.add(date);
//            
//        }
//        if( jCheckBox4.isSelected())
//        {
//            list.add("SE 133");
//            String date = dateFormat.format(cal.getTime());
//            dateList.add(date);
//            
//        }
//        if( jCheckBox5.isSelected())
//        {
//            list.add("SE 165");
//            String date = dateFormat.format(cal.getTime());
//            dateList.add(date);
//            
//        }
//        if( jCheckBox6.isSelected())
//        {
//            list.add("SE 185");
//            String date = dateFormat.format(cal.getTime());
//            dateList.add(date);
//           
//        }
//        if( jCheckBox7.isSelected())
//        {
//            list.add("SE 148");
//            String date = dateFormat.format(cal.getTime());
//            dateList.add(date);
//            
//        }
//        if( jCheckBox8.isSelected())
//        {
//            list.add("SE 149");
//             String date = dateFormat.format(cal.getTime());
//            dateList.add(date);
//            
//        }
//       if( jCheckBox9.isSelected())
//        {
//            list.add("SE 120");
//            String date = dateFormat.format(cal.getTime());
//            dateList.add(date);
//            
//        }
//       if( jCheckBox10.isSelected())
//        {
//            list.add("SE 166");
//             String date = dateFormat.format(cal.getTime());
//            dateList.add(date);
//            
//        }
//       if( list.size() > 4)
//       {
//           JOptionPane.showMessageDialog(null, "You cannot take more than 4 classes!", 
//                   "InfoBox: Error" + "Registration Class", JOptionPane.INFORMATION_MESSAGE);
//           list.clear();
//           dateList.clear();
//       }else if(list.size() == 0)
//       {
//           JOptionPane.showMessageDialog(null, "Choos a class to register!", 
//                   "InfoBox: Error" + "Registration Class", JOptionPane.INFORMATION_MESSAGE);
//       }
//       else {
//        String[] arrayObjectClass =(String[]) list.toArray(new String[list.size()]);
//        String[] arrayObjectDate = (String[]) dateList.toArray(new String[list.size()]);
//        AnyMedia log = new AnyMedia();
//        AnyMedia.ListClass.setListData(arrayObjectClass);
//        AnyMedia.ListDate.setListData(arrayObjectDate);
//         this.setVisible(false);
//        log.setVisible(true);
//       }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
  
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void String() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
